config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  
  resources :posts do
    resources :comments
  end

  get '/' => 'users#index'
  get '/users/new' => 'users#new'
  get 'posts' => 'posts#index'
  post '/posts' => 'posts#new'




  get '/signin' => 'sessions#new', as: :new_session
  post '/create-session' => 'sessions#create', as: :create_session
  get '/signout' => 'sessions#destroy', as: :destroy_session

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments

    validates_presence_of :email

    scope :created_today, -> {where("created_at BETWEEN ? AND ?", 
    Date.today.beginning_of_day, Time.now)}

    scope :created_on_date, -> (date) { where("created_at BETWEEN ? AND ?", date.beginning_of_day, date.end_of_day)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    #GET /comments/all
    def index
        @comments = Comment.all
    end

    #GET /comments/new
    def new
        @comment = Comment.new
        @comment = Comment.new(post_id: params[:post_id])
        @post = Post.find(params[:post_id])
    end

    #POST /comments
    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = session[:user_id]
        @post = params[:id]
        if @comment.save
          flash[:notice] = "comment created."
          redirect_to "/posts/#{params[:post_id]}"
        else
          flash[:error] = "Error creating comment."
          render '/'
        end
    end
    
    #GET /posts/:id/edit
    def edit
        @comment = Comment.find(params[:id])
        @post = Post.find(params[:post_id])
    end

    #PUT /posts/:id
    def update
        comment = Comment.find(params[:id])
        comment.update(comment_params)
        flash[:notice] = "Updated post."
        redirect_to "/posts/#{params[:post_id]}"
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to '/posts'
    end

    private
    def comment_params    
      params.require(:comment).permit(:user_id, :post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    #GET /posts/all
    def index
        @posts = Post.all
    end

    #GET /posts/new
    def new
        @post = Post.new
        
    end

    #GET /posts/:id
    def show 
         @post = Post.find(params[:id])
    end

    #GET /posts/:id/edit
    def edit
        @post = Post.find(params[:id])
        @user = User.find(session[:user_id])
    end

    #PUT /posts/:id
    def update
        post = Post.find(params[:id])
        post.update(post_params)
        flash[:notice] = "Updated post."
        redirect_to post
    end

    #POST /posts
    def create
        post = Post.new(post_params)
        post.user_id = session[:user_id]
        if post.save
            flash[:success] = 'created post'
            redirect_to post
        else
            flash[:error] = 'not logged in'
            redirect_to '/'
        # if session[:user_id] == nil
        #     flash[:notice] = "you are not logged in"
        # else
        #     flash[:notice] = "Created post."
        #     redirect_to post
        end
        
    end

    #DELETE /posts/:id
    def destroy
        Post.find(params[:id]).destroy
        flash[:notice] = "Destroyed post."
        redirect_to posts_path
    end

    private
    def post_params    
      params.require(:post).permit(:user_id, :body)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
  
    def create
      user = User.where(email: params[:email]).first
  
      if user.present? && user.password == params[:password]
        session[:user_id] = user.id
        flash[:notice] = "Logged in!"
        redirect_to users_path
      else
        flash[:notice] = "Email or password didn't match"
        redirect_to new_session_path
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to users_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
      end
    
    #GET /users/new
    def new
      @user = User.new
    end
  
    #GET /users/:id
    def show 
      @user = User.find(params[:id])
    end
  
    #GET /users/:id/edit
    def edit
      @user = User.find(params[:id])
    end
  
    #PUT /users/:id
    def update
      user = User.find(params[:id])
      user.update(user_params)
      flash[:notice] = "Updated user."
      redirect_to user
    end
  
    #POST /users
    def create
      user = User.new(user_params)
      if user.save
        flash[:notice] = "Created user."
        redirect_to user
      else
        flash[:notice] = "There was an error: "
        flash[:notice] += user.errors.full_messages.join(', ')
        redirect_to new_user_path
      end
    end
  
    #DELETE /users/:id
    def destroy
      @user = User.find(params[:id])
      @user.posts.each do |post|
        post.comments.destroy_all
      end
      @user.comments.destroy_all
      @user.posts.destroy_all
      if @user.destroy
      flash[:success] = "Destroyed user."
      else
      flash[:error] = "problem destroying user"
      end
      redirect_to users_path  
    end

    private
    def user_params    
      params.require(:user).permit(:name, :email, :password)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<div id="comment_form_div">
    <%= form_for ([@post, @comment]) do |f| %>
            <%= f.label :body %>
            <%= f.text_area :body, class: "text-area" %>
            <%= f.hidden_field :post_id %>
            <%= f.submit %>
    <% end %>
</div>

app/views/comments/edit.html.erb
<%= render 'form', comment: @comment %>

 <%= link_to("Delete Comment", post_comment_path, method: :delete) %>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
   
    <div id="login-message">
        <h4><% if session[:user_id] %></h4>
          <h3 id="logged-in"> <%= User.find(session[:user_id]).name %>, you are signed in! </h3>
          <% else %>
           <h4 id="logged-out"> Please login </h4>
        <% end %>
      </div>
     

    <div class='box'><a href = '/posts/'><div>Posts</div></a></div>
    
    <div class='box'><a href = '/users/'><div>Users</div></a></div>

    

    <%= flash[:notice] if flash[:notice] %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= f.label :WriteYourEdit %>
  <%= f.text_area :body %>
  <%= f.hidden_field(:user_id, value: @user.id) %>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<main id='posts-index'>
  <% @posts.reverse.each do |post| %>
      
      <div class='postBox'>
      <%= link_to(post.body, post) %> <br/>
        Post created by: <%= post.user.name %><br/>
      </div>
  <% end %>



  <p>
    <%= link_to('Create Post', new_post_path)%>
  </p>

  <% if session[:user_id] %>
     hi you are logged in!
    <%= link_to 'Signout', destroy_session_path%>
  <% else %>
    <%= link_to 'Signin', new_session_path %>
  <% end %>

</main>

app/views/posts/new.html.erb
<div id="post-form">
<%= form_for @post do |f| %>
  <%= f.label :WriteSomething %>
  <%= f.text_area :body, size: '40x40' %>
  
  <%= f.submit %>
<% end %>
</div>

<% if false %>
<%= f.hidden_field(:user_id, value: @user.id) %>
<% end %>

app/views/posts/show.html.erb
<%= @post.body %>

<%= link_to("Edit Post", edit_post_path(@post)) %><br>
<%= link_to("Delete Post", @post, method: 'delete') %><br>
<%= link_to("Add Comment", new_post_comment_path(post_id: @post.id)) %>

<h3><% @post.comments.reverse.each do |f| %> </h3> 
            <div id="single-comment">
                <h4>Comment</h4>
                <h5>From - <%= f.user.name %></h5>

                <h5><%= f.body %> </h5>

                <br>

                
                
                <a href ="/posts/<%=@post.id%>/comments/<%=f.id%>/edit">edit comment</a>
                <br>
               
                
            </div>
        <% end %>

<%=image_tag "dog1.jpeg" %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/index.html.erb
 <main id='users-index'>
  <% @users.each do |user| %>
      
      <p>
        Name: <%= user.name%><br/>
      </p>
      <%= link_to(user.email, user) %> 
  <% end %>



  <p>
    <%= link_to('Create User', new_user_path)%>
  </p>

  <p>
    <%= link_to('Create Post', new_post_path)%>
  </p>

  <% if session[:user_id] %>
     hi you are logged in!
    <%= link_to 'Signout', destroy_session_path%>
  <% else %>
    <%= link_to 'Signin', new_session_path %>
  <% end %>

</main>

app/views/users/new.html.erb
<%= render "form", user: @user %>

<% if @user.errors.full_messages.any? %>
 <ul>
 <% @user.errors.full_messages.each do |error_message| %>
 <li><%= error_message %></li> <br />
 <% end %>
 </ul>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>
<%= @user.email %>

<%= link_to("Edit User", edit_user_path(@user)) %>
<%= link_to("Delete User", @user, method: 'delete') %>

<%=image_tag "dog.jpeg" %>